name: Telegram to Discord Forwarder

concurrency:
  group: telegram-discord-forwarder
  cancel-in-progress: true

on:
  workflow_dispatch:  # permite rodar manualmente
  schedule:
    - cron: "*/15 * * * *"  # roda a cada 15 minutos

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python bot.py
